name: Deploy website
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: cache dependencies
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}     
          restore-keys: |
           ${{ runner.os }}-node-
       

      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
      filename: ${{ steps.set-filename.outputs.filename }}
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: cache dependencies
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}     
          restore-keys: |
           ${{ runner.os }}-node-
       
      - name: Install dependencies
        run: npm ci
      - name: Build website
        run: npm run build
      - name: Set filename output
        id: set-filename
        run: echo "filename=v${{ github.run_number }}" >> $GITHUB_OUTPUT
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ steps.set-filename.outputs.filename }}
          path: dist
  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: download Artifacts
        uses: actions/download-artifact@v7

        with:
          name: ${{ needs.build.outputs.filename }}
      - name: cache dependencies
        uses: actions/cache@v3
        with: 
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}     
          restore-keys: |
           ${{ runner.os }}-node-
      - name: Deploy
        run: echo "Deploying..."
